= jQAssistant GraphML Plugin

This is the http://graphml.graphdrawing.org/[GraphML^] Plugin of https://jqassistant.org[jQAssistant^].
It enables jQAssistant to generate GraphML XML files for result data of concepts.
Those files can be used with several graph rendering
and analytics tools like http://www.yworks.com/en/products/yfiles/yed/[yEd^] and http://gephi.org[Gephi^].

For more information on jQAssistant see https://jqassistant.org[^].

== Using the jqassistant-graphml-plugin

NOTE:: Starting from jqassistant-graphml-plugin v2.0.0, the GraphML-Plugin resides under jqassistant-plugin.
Therefore, not only the repository location changed but also group id and artifact id were adapted from `com.buschmais.jqassistant.plugin:graphml` to `org.jqassistant.plugin:jqassistant-graphml-plugin`.

NOTE:: From jQAssistant v2.0.0 onwards, it is not part of the core distribution anymore and a manual configuration as shown below is required.

[source, xml]
----
<plugin>
    <groupId>com.buschmais.jqassistant</groupId>
    <artifactId>jqassistant-maven-plugin</artifactId>
    <version>${jqassistant.version}</version>
    <executions>
        <execution>
            <id>default-cli</id>
            <goals>
                <goal>scan</goal>
                <goal>analyze</goal>
            </goals>
        </execution>
    </executions>
    <dependencies>
        <dependency> // <1>
            <groupId>org.jqassistant.plugin</groupId>
            <artifactId>jqassistant-graphml-plugin</artifactId>
            <version>${jqassistant.graphml-plugin.version}</version>
        </dependency>
    </dependencies>
</plugin>
----
<1> Dependency to the GraphmL plugin
