
name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch: {}

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: jqassistant-tooling/jqassistant-github-actions/.github/release-drafter.yml@main
        id: release_drafter
      - name: Display Checked Out Files
        run: ls -l
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
