
name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch: {}

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .github/release-drafter.yml
          name: my-other-artifact#
          repository: jqassistant-tooling/jqassistant-github-actions/.github/release-drafter.yml@main
      - name: Display Checked Out Files
        run: ls -l
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
